% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames*,x11names*}{xcolor}
%
\documentclass[
]{krantz}
\usepackage{pdfpages}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
  \setmonofont[Scale=0.7]{Source Code Pro}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Navigating Birth Defects in Nova Scotia},
  pdfauthor={Reproductive Care Program of Nova Scotia},
  colorlinks=true,
  linkcolor=Maroon,
  filecolor=Maroon,
  citecolor=Blue,
  urlcolor=Blue,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{pdfpages}
\frontmatter
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

\title{Navigating Birth Defects in Nova Scotia}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{A Ten Year Perspective\\
2012-2022}
\author{Reproductive Care Program of Nova Scotia}
\date{Jan, 2024}

\begin{document}
\pagestyle{empty}
\includepdf{images/cover5.pdf}
\setcounter{page}{1}
\maketitle
\thispagestyle{empty}
\newpage


{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{3}
\tableofcontents
\newpage
}


\hypertarget{background}{%
\chapter*{Background}\label{background}}


Gaps exist in the nation's capacity to conduct surveillance for congenital anomalies. In \(2002\), the Canadian Congenital Anomalies Surveillance Network (CCASN) was established

\begin{quote}
To support the development and maintenance of high quality population-based surveillance systems of congenital anomalies that will provide information to improve the health of Canadian children and their families.\footnote{\href{http://www.phac-aspc.gc.ca/ccasn-rcsac/index-eng.php}{Public Health Agency of Canada. What is Canadian Congenital Anomalies Surveillance Network (CCASN)}}
\end{quote}

The CCASN produced a series of documents regarding the establishment of provincial/territorial surveillance systems for congenital anomalies\footnote{\href{https://www.canada.ca/en/public-health/services/health-promotion/what-is-ccasn/guidelines.html}{Canadian Congenital Anomalies Surveillance Network. Recommendations concerning the establishment of congenital anomalies surveillance in Canadian jurisdictions.}}, coding of congenital anomalies\footnote{\href{https://health-infobase.canada.ca/congenital-anomalies/}{Canadian Congenital Anomalies Surveillance Network. Coding of fetal anomalies.}}, and delineating data elements required for minimal and enhanced surveillance for congenital anomalies\footnote{\href{https://www.phac-aspc.gc.ca/ccasn-rcsac/sac-cas/pdf/cas-eng.pdf}{Canadian Congenital Anomalies Surveillance Network. Recommended data variables for congenital anomalies surveillance in Canadian provinces \& territories.}}.

In Nova Scotia, data regarding congenital anomalies diagnosed at birth or during the birth admission have been collected since \(1987\) in the Nova Scotia Atlee Perinatal Database (NSAPD) managed by the Reproductive Care Program of Nova Scotia (RCP). The NSAPD collects data about all live born infants and stillbirths for all fetuses delivered \(\ge 20\) weeks gestation, or \(\ge 500\) grams, or live born and all co-multiples of the aforementioned; the NSAPD also captures information about the mothers of the infants/fetuses mentioned above. The NSAPD does not capture data for congenital anomaly cases identified during admissions that occur after \(28\) days of age. The NSAPD also does not capture data for pregnancies ending in termination.

Since \(1992\), data regarding congenital anomalies diagnosed antenatally, or postnatally up to the time of discharge from the IWK Health Centre, or on the basis of an autopsy have been captured through the Fetal Anomaly Database (FADB) housed at the Division of Maternal and Fetal Medicine, IWK Health Centre. The IWK is the only obstetrics/paediatric tertiary care centre in the Maritimes; as such, the FADB captures most congenital anomaly cases in Nova Scotia resulting in live births, still births, and terminations. The FADB does not capture congenital anomaly cases diagnosed after the birth admission, many of which are present in other data sources within the province. The FADB also uses an in-house coding system to classify anomalies, a practice that predates the CCASN recommendation to use the Royal College of Paediatrics and Child Health codes (adapted from the \href{https://www.google.ca/url?sa=t\&rct=j\&q=\&esrc=s\&source=web\&cd=\&ved=2ahUKEwi9rdLH6pT7AhU2kIkEHUtrDgIQFnoECBgQAQ\&url=https\%3A\%2F\%2Fapps.who.int\%2Firis\%2Fbitstream\%2Fhandle\%2F10665\%2F246208\%2F9789241549165-V1-eng.pdf\&usg=AOvVaw1TYOJuoOf2vUt7kCVsCziR}{International Statistical Classification of Diseases and Related Health Problems, 10th Revision -- ICD-10}).

\hypertarget{scan-ns-activity-and-report-summary}{%
\chapter*{SCAN-NS Activity and Report Summary}\label{scan-ns-activity-and-report-summary}}


\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  This is the first provincial report on the prevalence of congenital anomalies in Nova Scotia generated by the Surveillance of Congenital Anomalies in Nova Scotia project (SCA-NS).
\item
  The International Classification of Diseases - \(10^{th}\) Edition \href{https://secure.cihi.ca/estore/productSeries.htm?pc=PCC189}{(ICD-10-CA)} has been adopted by the IWK Health Centre as the reporting classification system and SCA-NS uses the Royal College of Paediatrics and Child Health adaptation of ICD-10 as well. The anomalies outlined in this report reflect the ``sentinel anomalies list'' adopted by the Nova Scotia Congenital Anomaly Advisory Group. Other anomaly data is collected and available upon request.
\item
  Nova Scotia continues to participate in the Canadian Congenital Anomalies Surveillance System (CCASS), administered by the Maternal and Infant Health Section of PHAC.
\item
  The numerator data include live births, stillbirths, and also fetal losses \(< 20\) weeks gestation with congenital anomalies. Denominator data include live births and stillbirths only. By including fetal losses in the numerator, the reported rates should be more representative of true congenital anomaly rates. Fetal losses have been ascertained since \(1992\).
\item
  Data provided in this report is a compilation of several data Nova Scotia databases.
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Nova Scotia Atlee Perinatal Database (NSAPD).
\item
  Fetal Anomaly Database (FADB).
\item
  Canadian Institute for Health Information Discharge Abstract Database.
\item
  Vital Statistics Database; Service Nova Scotia.
\item
  Medical Services Insurance (MSI) Claims.
\end{itemize}

\hypertarget{introduction}{%
\chapter*{Introduction}\label{introduction}}


The purpose of SCA-NS is to improve Congenital Anomaly case ascertainment, cluster detection, local and national data comparison and reporting capability. Program objectives
- Provide baseline data on occurrence.
- Identify populations at increased risk.
- Monitor changes in occurrence.
- Investigate clusters.
- Refer affected children to services.
- Evaluate prevention programs.
- Create research opportunities.

SCA-NS includes all Nova Scotia residents, with ascertainment from other Maritime Provinces for those cases where the mother delivered elsewhere. Information on cases includes the prenatal period up to one year of age including live births, stillbirths and terminations of pregnancies in which a fetal anomaly has been detected.

\mainmatter

\hypertarget{chapter1}{%
\chapter{Methodology}\label{chapter1}}

\hypertarget{section11}{%
\section{Case Definitions}\label{section11}}

A congenital anomaly is an abnormality that is present at birth, even if not diagnosed until months or years later. Most congenital anomalies are present long before the time of birth, some in the embryonic period (up to the end of the seventh week of gestation) and others in the fetal period (eighth week to term). The term ``anomaly'' covers all the major classes of abnormalities of development, of which there are four major categories as follows:

\begin{itemize}
\item
  \textbf{Malformation -} a morphologic defect of an organ, part of an organ or a larger region of the body resulting from an intrinsically abnormal developmental process (e.g., spina bifida, cleft lip and palate).
\item
  \textbf{Deformation -} an abnormal form, shape or position of a part of the body caused by mechanical forces (e.g., extrinsic force such as intrauterine constraint causing some forms of clubfoot).
\item
  \textbf{Disruption -} a morphologic defect of an organ, part of an organ or a larger region of the body resulting from the extrinsic breakdown of, or an interference with, an originally normal developmental process (e.g., an infection such as rubella or a teratogen such as thalidomide).
\item
  \textbf{Dysplasia -} the abnormal organization of cells into tissues and its morphologic result (e.g., Marfan Syndrome, osteogenesis imperfecta).
\end{itemize}

Other definitions related to pregnancy outcomes for the purposes of this report are as follows:

\begin{itemize}
\item
  \textbf{Live birth -} a complete expulsion or extraction from the mother, irrespective of the duration of the pregnancy, of a fetus in which, after expulsion or extraction, there is breathing, beating of the heart, pulsation of the umbilical cord or definite movement of voluntary muscle (Alberta Vital Statistics Annual review, 2000).
\item
  \textbf{Stillbirth -} a complete expulsion or extraction from the mother, after at \(20\) weeks of pregnancy or more or after attaining a weight of 500 grams or more, of a fetus in which, after the expulsion or extraction, there is no breathing, beating of the heart, pulsation of the umbilical cord or unmistakable movement of voluntary muscle (Alberta Vital Statistics Annual review\footnote{\href{https://open.alberta.ca/publications/1485-3809}{Alberta Vital Statistics Annual review}}.
\end{itemize}

\begin{itemize}
\item
  \textbf{Gestation -} completed weeks of pregnancy at delivery.
\item
  \textbf{Preterm birth (a.k.a premature) -} a birth before \(37\) weeks of gestation (\(< 37\) weeks).
\item
  \textbf{Termination of Pregnancy (ToP) -} for our purposes, includes any pregnancy loss before 20 weeks gestation (\(< 20\) weeks). Most cases are therapeutic terminations for congenital anomalies but spontaneous abortions or intrauterine fetal deaths with fetal anomalies could also be included.
\end{itemize}

Anomaly definitions are based, for the most part, on those provided by the International Clearinghouse for Birth Defects Surveillance and Research (ICBDSR) and National Birth Defects Prevention Network (NBDPN).

\hypertarget{section12}{%
\section{Case Acertainment}\label{section12}}

An infant can be ascertained at any time up to the first birthday. Multiple ascertainment of the same infant can occur and is encouraged, as this frequently improves the quality and reliability of the data.

As several malformations may occur in the same infant, it is advantageous to allow each to be reported so that groups of associated malformations may be studied. This, however, leads to difficulties since the final tabulations may be reported as total malformations (anomaly rates) or as the total number of malformed infants (case rates). The tables in {[}Appendix A3{]} report anomaly rates, which in most cases are similar to case rates (e.g.~cleft palate, hypospadias, microcephaly. Whereas with limb anomalies, there can be multiple different limb anomalies in the same infant.

SCA-NS obtains information about infants with congenital anomalies from a variety of independent sources. Acquisition of additional reporting agencies is always a priority since the use of multiple sources of information improves not only the ease but also completeness of ascertainment as well as for verification of the diagnostic data.

\hypertarget{section13}{%
\section{Quality Control Measures and Data Linkage}\label{section13}}

Data quality is ensured through both a coded linking process and by manual chart audits of unmatched anomaly records. The first step in data quality control involves the linking of disparate fetal/infant records between databases. Linking is based on the matching of several unique variables in each record.

\begin{itemize}
\item
  If two records ``pass'': this variable matching process, the records are considered link and therefore report anomalies on the same fetus/infant. This allows SCA-NS to create a record that reports anomalies from several databases for the same fetus/infant.
\item
  If there are records that ``fail'' the automated matching process they are reviewed manually to determine if that information was only found in one data source or if information was entered incorrectly.
\end{itemize}

\hypertarget{section14}{%
\section{Confidentiality and Release of Data}\label{section14}}

\hypertarget{authority-for-the-collection-use-and-disclosure-of-personal-information}{%
\subsection*{Authority for the Collection, Use, and Disclosure of Personal Information}\label{authority-for-the-collection-use-and-disclosure-of-personal-information}}


In Nova Scotia, personal health information is protected by legislation, policies, and professional codes of ethics of healthcare providers. SCA-NS will follow the provisions outlined in the IWK's Privacy of Personal Health Information policy and the RCP Privacy Policy\footnote{ \href{http://rcp.nshealth.ca/about/privacy-personal-information}{RCP Privacy Policy}} and the Data Access for Research and Planning Policy and Procedures\footnote{ \href{https://rcp.nshealth.ca/sites/default/files/atlee-database/nsapd_data_access_policy_nov2007.pdf}{Data Access for Research and Planning Policy and Procedures}}

\hypertarget{data-requests}{%
\subsection*{Data Requests}\label{data-requests}}


Data requests will be reviewed by a sub-committee of the Joint Perinatal Epidemiology Research Unit-Population Health Research Unit-RCP Data Access Committee (JDAC). Clinical and technical staff will participate, as will representatives from all stakeholders currently involved in providing data, i.e.~Maternal-Fetal Medicine, BIAP, both with a privacy and a technical representative, and other groups such as Cardiology, as the database develops. Disclosure for research purposes also requires approval by a recognized Research Ethics Board and, if approved, a Data Use Agreement. SCA-NS will only consider disclosing individual level data (with or without personal identifiers) following a technical review and approval from a specially-constituted committee.

\hypertarget{limitations-of-data-and-analysis}{%
\subsection*{Limitations of Data and Analysis}\label{limitations-of-data-and-analysis}}


One of the major limitations of any surveillance system is that on its own, the information provided does not allow etiology to be determined. If trends indicate a potential problem, then separate investigative studies need to be done. However, with appropriate approvals in place, it would be possible to conduct linkage studies with other data sources to explore potential causes of specific birth defects. SCA-NS data are collected passively from a variety of sources and the completeness and accuracy of data are largely dependent on reporting and coding of several different organizations. SCA-NS reviews anomalies that have been entered into the database on a regular basis. Detailed studies of some individual anomalies or anomaly groups aid in the assessment and maintenance of the data quality. With intensive review, some cases might be reassigned, re-coded or discarded altogether from the database. This continuing review might explain some discrepancies in the data from earlier reports.

\hypertarget{epidemiological-and-statistical-measures}{%
\subsection*{Epidemiological and Statistical Measures}\label{epidemiological-and-statistical-measures}}


\begin{itemize}
\tightlist
\item
  Unless otherwise stated, all the formulas used to compute prevalence and confidence intervals are calculated following the \href{http://www.nbdpn.org/docs/Ch_8_Statistics6-04_2016DEC14.pdf}{National Birth Defects Prevention Network (NBDPN) guidelines, chapter 8}:
\end{itemize}

\begin{quote}
\[
\substack{\text{Prevalence} \\ \\ \text{at birth}} = 1,000 \times \dfrac{\text{Number of cases with birth defect A in an area and time period}}{\text{Number of live births and stillbirths in that area and time period}}
\]
\end{quote}

\begin{itemize}
\tightlist
\item
  \textbf{Pregnancy outcomes included -} the cases in the \textbf{numerator} are derived from all pregnancy outcomes collected by the program and may include:

  \begin{itemize}
  \tightlist
  \item
    Live births.
  \item
    Stillbirths.
  \item
    Termination of pregnancy (ToP): all fetal losses \(< 20\) weeks gestation with congenital anomalies.
  \end{itemize}
\end{itemize}

For the \textbf{denominator}, we use the total number of live births and stillbirths in the same area and time period from which the cases were ascertained.

\hypertarget{confidence-intervals}{%
\subsubsection*{Confidence intervals}\label{confidence-intervals}}


(\(95\%\)) confidence intervals are also included because the rate obtained is actually only a point estimate of the unknown, true population rate. The confidence interval provides information about the precision of the estimate. Thus, the confidence intervals are an estimated range of values within which there is a \(95\%\) probability that the true population rate will fall.

\begin{itemize}
\tightlist
\item
  \textbf{\emph{For a prevalence based on a small number of cases -}} For small numbers of cases (arbitrarily defined here as \(< 30\) cases), we use the Poisson distribution since birth defects are considered to be rare events. The easiest way to use the Poisson distribution is to refer to a table that provides the upper and lower \(95\%\) confidence limits for an observed number of cases. For that, we make use of the relationship between the Poisson and chi-square distribution functions. If \(X\) is a single observation from a Poisson distribution with mean \(\mu\). Then the ``exact'' \(95\%\) confidence limits for \(\mu\) are given by
\end{itemize}

\begin{quote}
\[
\small{
\left[\dfrac{qchisq\left(0.025, 2X\right)}{2}; \dfrac{qchisq\left(0.975, 2(X+1)\right)}{2}\right]},
\]
\end{quote}

where \(qchisq()\) is the quantile function for the chi-squared \(\left(\chi^{2}\right)\) distribution with \(2X\), and \(2(X+1)\) degrees of freedom. These limits can be computed using any statistical software or taken from a chi-square table (reproduced below for up to \(5\) cases).

\begin{table}

\caption{\label{tab:pois1}}
\centering
\begin{tabular}[t]{rrr}
\toprule
Number of Cases & Lower Bound & Upper Bound\\
\midrule
0 & 0.000 & 3.689\\
1 & 0.025 & 5.572\\
2 & 0.242 & 7.225\\
3 & 0.619 & 8.767\\
4 & 1.090 & 10.242\\
\addlinespace
5 & 1.623 & 11.668\\
\bottomrule
\end{tabular}
\end{table}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Calculate prevalence
\end{enumerate}

\begin{quote}
\[\small{
1,000 \times \dfrac{\text{Number of cases with birth defect A in an area and time period}}{\text{Number of live births and stillbirths in that area and time period}}
}\]
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Look up the lower and upper \(95\%\) confidence limit for the number of cases with birth defect A. Using this new number in the numerator calculate the lower and upper \(95\%\) confidence limit for prevalence.
\end{enumerate}

\begin{quote}
\[
\scriptsize
\begin{aligned}
\substack{\text{Lower } 95\% \\ \\ \text{ CL for prevalence}} &= 1,000 \times \dfrac{\text{Lower } 95\% \text{ CL for cases with birth defect A in an area and time period}}{\text{Number of live births and stillbirths in that area and time period}}\\
\substack{\text{Upper } 95\% \\ \\ \text{ CL for prevalence}} &= 1,000 \times \dfrac{\text{Upper } 95\% \text{ CL for cases with birth defect A in an area and time period}}{\text{Number of live births and stillbirths in that area and time period}} 
\end{aligned}
\]
\end{quote}

\textbf{Example -} Considering that for a birth defect A in an area and time period we had \(5\) cases with a number of total births of \(12,500\) we have

\begin{quote}
\[
\small
\begin{aligned}
\text{Prevalence} &= 1,000 \times \dfrac{5}{12,500} = 0.4  \\
\substack{\text{Lower } 95\% \\ \\ \text{ CL for prevalence}} &= 1,000 \times \dfrac{1.623}{12,500} = 0.13 \\
\substack{\text{Upper } 95\% \\ \\\text{ CL for prevalence}} &= 1,000 \times \dfrac{11.668}{12,500} = 0.93 
\end{aligned}
\]
\end{quote}

\begin{itemize}
\item
  \textbf{\emph{For a prevalence based on a large number of cases -}} For a large number of cases (arbitrarily defined here as \(\ge 30\) cases), use the Normal distribution because as the number of cases grows larger, the Poisson distribution approximates the Normal distribution.
  Let \(c=\text{number of cases in an area and time period}\) and \(b=\text{number of live births and stillbirths in an area and time period}\)

  \begin{enumerate}
  \def\labelenumi{\arabic{enumi}.}
  \tightlist
  \item
    Calculate the lower and upper confidence limit using the following:
  \end{enumerate}
\end{itemize}

\begin{quote}
\[
\small
\begin{aligned}
\substack{\text{Lower } 95\% \\ \\ \text{ CL for prevalence}} &= 1,000 \times \dfrac{\left( 1- \dfrac{1}{9c}-\dfrac{1.96}{3}\sqrt{\dfrac{1}{c}} \right)^{3}}{b}\times c \\
\substack{\text{Upper } 95\% \\ \\ \text{ CL for prevalence}} &= 1,000 \times \dfrac{\left( 1- \dfrac{1}{9\left(c+1\right)}+\dfrac{1.96}{3}\sqrt{\dfrac{1}{\left(c+1\right)}} \right)^{3}}{b}\times \left(c+1\right) 
\end{aligned}
\]
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  To determine different \(\left(1 - \alpha \right) \%\) confidence limits, replace \(1.96\) with the corresponding value from the Normal distribution.
\item
  To obtain confidence limits for the number of cases instead of the prevalence, apply the formulae but do not divide by \(b=\) number of live births and stillbirths in an area and time period or multiply by \(1,000\).
\end{enumerate}

\hypertarget{trend-analysis}{%
\subsubsection*{Trend analysis}\label{trend-analysis}}


When appropriate, \textbf{trend analysis} are performed. Since our response variable of interest is the number of cases, there is no fixed upper bound \(n\) for it. Since number of cases must take a non-negative integer value, its distribution should place its mass on that range.

The simplest such distribution is the \textbf{\emph{Poisson}}. Its probabilities depend on a single parameter, the mean \(\mu\). The Poisson distribution is used for counts of events that occur randomly over time or space, when outcomes in disjoint periods or regions are independent. It satisfies \(E\left(X\right)=Var\left(X\right)=\mu\). It approaches normality as \(\mu\) increases.

In the context of prevalence, the response count \(X_{i}\) has and index \(t_{i}\) such that its expected value is proportional to \(t_{i}\). Our approach here, is to consider the total births as the index, since this value varies over time. Then , our sample rate is \(x_{i}/t_{i}\), with expected value \(\mu_{i}/t_{i}\). A log-linear model for the expected rate has form

\begin{quote}
\[
\begin{aligned}
log\left(\mu_{i}/t_{i}\right) &= \beta_{0} + \beta_{1}(Year)  \\
log\left(\mu_{i}\right) - log\left(t_{i}\right) &= \beta_{0} + \beta_{1}(Year)  \\
log\left(\mu_{i}\right) &= \beta_{0} + \beta_{1}(Year) + log\left(t_{i}\right)
\end{aligned}
\]
\end{quote}

The adjustment term \(-log\left(t_{i}\right)\), to the log link of the mean is called an \emph{offset}. Another option is to run this model using the identity link. The model is then

\begin{quote}
\[
\begin{aligned}
\mu_{i}/t_{i} &= \beta_{0} + \beta_{1}(Year)  \\
\mu_{i} &= \beta_{0}t_{i} + \beta_{1}(Year)t_{i}
\end{aligned}
\]
\end{quote}

which does not require an offset. It corresponds to an ordinary Poisson GLM using the identity link with no intercept and exploratory variables \(t_{i}\), \((Year)t_{i}\) and its estimates are equal to an OLS model without an intercept.

Since we are working with the observed rater per 1,000 total births, adjusting the yearly count by total births is equivalent to have \(t_{i} = \text{total births}/1,000\).

Sometimes, one can note that the count data could show great variability. Under a Poisson model, we would expect the means and variances of the response to be about the same in various groups. A severe limitation of Poisson models is that \(E \left(X \right) = Var \left(X \right) = \mu\). Hence, at a fixed mean the variance cannot decrease as additional predictors enter the model. The greater variability than predicted by the GLM random component reflects \textbf{overdispersion}. A common cause of overdispersion is subject heterogeneity. Without adjusting for overdispersion, we use incorrect, artificially small standard errors leading to artificially small p-values for model coefficients which may lead to wrong inferences and conclusions.

We can take overdispersion into account in several different ways. The simplest is to use an estimated dispersion factor to inflate standard errors. Another way is to use a \textbf{negative-binomial} regression model. In this case, \(E\left(X\right)= \mu\), and \(Var \left( X \right) = \mu + \gamma \cdot \mu^{2}\). The index \(\gamma > 0\) is a type of dispersion parameter. As \(\gamma \rightarrow 0\), \(Var \left( X \right) \rightarrow \mu\) and the negative binomial distribution converges to the Poisson.

For the aforementioned model,

\begin{quote}
\[
\mu_{i} = \beta_{0}t_{i} + \beta_{1}(Year)t_{i}
\]
\end{quote}

significance tests focus on \(H_{0}: \beta_{1} =0\). The Wald test uses the log-likelihood at \(\hat{\beta_{1}}\), with test statistic \(z=\hat{\beta_{1}} / SE(\hat{\beta_{1}})\) or its square. Under \(H_{0}\), \(z^{2}\) is asymptotically \(\chi^{2}_{1}\). At a \(5\%\) level, any p-value lower than \(5\%\) would provide evidences against \(H_{0}\), meaning that at a \(5\%\) level they would be considered statistically significant.

\hypertarget{chapter2}{%
\chapter{Patterns of Selected Congenital Anomalies in Nova Scotia}\label{chapter2}}

\hypertarget{section21}{%
\section{Selected Anomalies}\label{section21}}

\hypertarget{section211}{%
\subsection{Selected Anomaly Definitions}\label{section211}}

All the birth defects descriptions and respective ICD10 codes were adapted from the \href{https://www.nbdpn.org/docs/SGSC_-_Ch3_Case_Definition_-_final_draft_2016DEC20.pdf}{National Birth Defects Prevention Network (NBDPN) guidelines, chapter 3}

\hypertarget{section2111}{%
\subsubsection{Neural tube defects}\label{section2111}}

\begin{itemize}
\tightlist
\item
  \textbf{Anencephaly and similar malformations (Q00)}
\end{itemize}

Partial or complete absence of the brain and skull.

\begin{itemize}
\tightlist
\item
  \textbf{Encephalocele (Q01)}
\end{itemize}

Herniation of brain tissue and/or meninges through a defect in the skull. The hernia sac is usually covered by skin.

\begin{itemize}
\tightlist
\item
  \textbf{Spina bifida (Q05)}
\end{itemize}

Incomplete closure of the vertebral spine (usually posteriorly) through which spinal cord tissue and/or the membranes covering the spine (meninges) herniate.

\hypertarget{section2112}{%
\subsubsection{Selected central nervous system defects}\label{section2112}}

\begin{itemize}
\tightlist
\item
  \textbf{Microcephaly (Q02)}
\end{itemize}

Microcephaly, or microcephalus, is the clinical finding of a small head when compared with infants of the same sex and age. The head circumference (HC), also known as the occipitofrontal circumference (OFC), is considered a reliable assessment of the volume of the underlying brain. Microcephaly itself is not a malformation but a sign that the brain is abnormally small.

\begin{itemize}
\tightlist
\item
  \textbf{Congenital hydrocephalus (Q03)}
\end{itemize}

An increase in the amount of cerebrospinal fluid within the brain resulting in enlargement of the cerebral ventricles and increased intracranial pressure.

\begin{itemize}
\tightlist
\item
  \textbf{Arhinencephaly/Holoprosencephaly (Q04.1, Q04.2)}
\end{itemize}

Arhinencephaly is an older term for holoprosencephaly which refers more specifically to structural defects of the olfactory system or nose. Holoprosencephaly results from variable degrees of incomplete division of the brain into right and left cerebral hemispheres. There are four types which vary in severity: alobar, semi-lobar, lobar, and middle interhemisphereic (MIHV). The condition can also affect development of the face and eyes. The most severely affected have one central eye (cyclopia) and a single tubular-shaped nose located above the eye (proboscis).

\hypertarget{section2113}{%
\subsubsection{Selected sense organ defects}\label{section2113}}

\begin{itemize}
\tightlist
\item
  \textbf{Anophtalmos/Microphtalmos (Q11.0, Q11.1, Q11.2)}
\end{itemize}

Anophthalmia is the total absence of eye tissue or apparent absence of the globe of the eye in an otherwise normal orbit. Microphthalmia is the reduced volume of the eye. The corneal diameter is usually less than 10 millimeters, or the anteroposterior globe diameter is less than 20 millimeters. Anophthalmia or microphthalmia may affect one or both eyes, or there may be anophthalmia of one eye and microphthalmia of the other.

\begin{itemize}
\tightlist
\item
  \textbf{Anotia/Microtia (Q16.0, Q17.2)}
\end{itemize}

Anotia is the total absence of the external ear and canal. Microtia is the malformation or hypoplasia of the external ear (auricle, pinna).

\begin{itemize}
\tightlist
\item
  \textbf{Choanal atresia (Q30.0)}
\end{itemize}

Congenital obstruction of the opening of the nasal cavity into the nasopharynx on either side. This prevents communication of the nasal cavity with the pharynx.

\hypertarget{section2114}{%
\subsubsection{Selected congenital heart defects}\label{section2114}}

\begin{itemize}
\tightlist
\item
  \textbf{Commom truncus (Q20.0)}
\end{itemize}

Failure of separation of the aorta and the pulmonary artery during development, resulting in a single common arterial trunk carrying blood from the heart to both the body and lungs.

\begin{itemize}
\tightlist
\item
  \textbf{Transposition of great vessels (Q20.1, Q20.3, Q20.5)}
\end{itemize}

Transposition of the aorta and the pulmonary artery such that the aorta arises
from the right ventricle (instead of the left) and the pulmonary artery arises from the left ventricle (instead of the right).

\begin{itemize}
\tightlist
\item
  \textbf{Atrioventricular septal defect (Q21.2)}
\end{itemize}

A defect in both the lower portion of the atrial septum and the upper portion of the ventricular septum. In extreme cases, virtually the entire atrial and ventricular septae may be missing. The valves controlling blood flow from the atria to the ventricles, the tricuspid and mitral valves may also be abnormal. They may not form from the endocardial cushions during cardiac development into two separate valves, and thus be a single common atrioventricular valve. Together, these defects producing a large opening (canal) in the central part of the heart.

\begin{itemize}
\tightlist
\item
  \textbf{Tetralogy of Fallot (Q21.3)}
\end{itemize}

Congenital obstruction of the opening of the nasal cavity into the nasopharynx on either side. This prevents communication of the nasal cavity with the pharynx.

\begin{itemize}
\tightlist
\item
  \textbf{Hypoplastic left heart syndrome (Q23.4)}
\end{itemize}

A condition in which the structures on the left side of the heart and the aorta are extremely small, insufficient to support systemic circulation and with normally related great arteries. Classically, this condition includes hypoplasia of the left ventricle, atresia or severe hypoplasia of both the mistral and aortic valves, hypoplasia of the aortic arch, and coarctation of the aorta.

\begin{itemize}
\tightlist
\item
  \textbf{Coarctation of aorta (Q25.1)}
\end{itemize}

Narrowing of the descending aorta, which may obstruct blood flow from the heart to the rest of the body. The most common site of coarctation occurs distal to the origin of the left subclavian artery in the region of the ductus arteriosus. If there is complete loss of communication in this location, it is a form of interruption of the aorta (Type A).

\hypertarget{section2115}{%
\subsubsection{Oro-facial clefts}\label{section2115}}

\begin{itemize}
\tightlist
\item
  \textbf{Cleft palate (Q35, excluding Q35.7)}
\end{itemize}

An opening in the roof of the mouth resulting from incomplete fusion of the shelves of the palate. The opening may involve the hard palate only, the soft palate only, or both.

\begin{itemize}
\tightlist
\item
  \textbf{Cleft lip (Q36)}
\end{itemize}

A defect in the upper lip resulting from incomplete fusion of the parts of the lip.

\begin{itemize}
\tightlist
\item
  \textbf{Cleft palate with cleft lip (Q37)}
\end{itemize}

A defect in the upper lip resulting from incomplete fusion of the parts of the lip, with an opening in the roof of the mouth.

\hypertarget{section2116}{%
\subsubsection{Selected gastrointestinal defects}\label{section2116}}

\begin{itemize}
\tightlist
\item
  \textbf{Oesophageal atresia/stenosis, tracheoesophageal fistula (Q39.0-Q39.4)}
\end{itemize}

Esophageal atresia is condition in which the esophagus ends in a blind pouch and fails to connect with the stomach. Tracheoesophageal fistula is an abnormal communication between the esophagus and the trachea. This is almost always associated with some form of esophageal atresia.

\begin{itemize}
\tightlist
\item
  \textbf{Small intestine absence/atresia/stenosis (Q41)}
\end{itemize}

Complete or partial occlusion of the lumen of one or more segments of the small intestine. Small intestinal atresias are often assigned a type descriptor in the surgical or autopsy report, depending upon the severity of the atresia (types include I, II, IIIA, IIIB, and VI).

\begin{itemize}
\tightlist
\item
  \textbf{Ano-rectal absence/atresia/stenosis (Q42.0-Q42.3)}
\end{itemize}

Complete or partial occlusion of the lumen of one or more segments of the large intestine and/or rectum.

\begin{itemize}
\tightlist
\item
  \textbf{Hirschsprung disease (Q43.1)}
\end{itemize}

Also called congenital aganglionic megacolon is a condition that affects the large intestine (colon) and causes problems with passing stool.

\begin{itemize}
\tightlist
\item
  \textbf{Atresia of bile ducts (Q44.2)}
\end{itemize}

Congenital absence of the lumen of the extrahepatic bile ducts.

\hypertarget{section2117}{%
\subsubsection{Selected genital anomalies}\label{section2117}}

\begin{itemize}
\tightlist
\item
  \textbf{Cryptorchidism/undescended testicles (Q53.1, Q53.2, Q53.9)}
\end{itemize}

A testicle that hasn't moved into its proper position in the bag of skin hanging below the penis (scrotum) before birth.

\begin{itemize}
\tightlist
\item
  \textbf{Hypospadias (Q54, excluding Q54.4)}
\end{itemize}

Displacement of the opening of the urethra (urethral meatus) ventrally and proximally (underneath and closer to the body) in relation to the tip of the glans of the penis.

\begin{itemize}
\tightlist
\item
  \textbf{Indeterminate sex (Q56)}
\end{itemize}

In a baby with ambiguous genitalia, the genitals may be incompletely developed or the baby may have characteristics of both sexes. The external sex organs may not match the internal sex organs or genetic sex. Pseudohermaphroditism - is a condition in which the individual has a single chromosomal and gonadal sex but combines features of both sexes in the external genitalia, causing doubt as to the true sex

\begin{itemize}
\tightlist
\item
  \textbf{Epispadias (Q64.0)}
\end{itemize}

Displacement of the opening of the urethra dorsally and proximally (on the top and closer to the body) in relation to the tip of the glans of the penis.

\hypertarget{section2118}{%
\subsubsection{Selected urinary tract defects}\label{section2118}}

\begin{itemize}
\tightlist
\item
  \textbf{Renal agenesis (Q60.0-Q60.2)}
\end{itemize}

Complete absence of the kidney.

\begin{itemize}
\tightlist
\item
  \textbf{Cystic kidney (Q61.1-Q61.5, Q61.8, Q61.9)}
\end{itemize}

Genetic disorder characterized by the formation of fluid-filled sacs (cysts) in the kidneys

\begin{itemize}
\tightlist
\item
  \textbf{Bladder and cloacal exstrophy (Q64.1)}
\end{itemize}

Bladder exstrophy is a defect in the lower abdominal wall and anterior wall of the bladder through which the lining of the bladder is exposed to the outside. Cloacal exstrophy is a congenital persistence of a common cloacal cavity into which gut, urethra, and reproductive tracts open with exstrophy of the cavity: usually accompanied by a low omphalocele, imperforate anus, and a (closed) neural tube defect.

\begin{itemize}
\tightlist
\item
  \textbf{Lower urinary tract obstruction (Q64.2, Q64.3)}
\end{itemize}

Posterior urethral valves (PUV) are tissue folds of the posterior urethra and function as valves obstructing urine outflow. Congenital PUV is an abnormal congenital obstructing membrane that is located within the posterior male urethra; this valve is the most common cause of bladder outlet obstruction in male children. Congenital PUV can also be found in virilized females and rarely in normal females. Obstruction could vary from mild to severe.

\hypertarget{section2119}{%
\subsubsection{Hip dysplasia (Q65)}\label{section2119}}

Hip dysplasia occurs when a baby's hip socket (acetabulum) is too shallow to cover the head of the thighbone (femoral head) to fit properly.

\hypertarget{section21110}{%
\subsubsection{Limb deficiency defects (Q71-Q73)}\label{section21110}}

Complete or partial absence of the upper arm (humerus), lower arm (radius and/or ulna), wrist (carpals), hand (metacarpals), fingers (phalanges), thigh (femur), lower leg (tibia and/or fibula), ankle (tarsals), foot (metatarsals), or toes (phalanges).

\hypertarget{section21111}{%
\subsubsection{Selected abdominal wall defects}\label{section21111}}

\begin{itemize}
\tightlist
\item
  \textbf{Diaphragmatic hernia (Q79.0)}
\end{itemize}

Incomplete formation of the diaphragm through which a portion of the
abdominal contents herniate into the thoracic cavity.

\begin{itemize}
\tightlist
\item
  \textbf{Omphalocele/Exomphalos (Q79.2)}
\end{itemize}

A defect in the anterior abdominal wall in which the umbilical ring is widened, allowing herniation of abdominal organs, including the small intestine, part of the large intestine, and occasionally the liver and spleen, into the umbilical cord. The herniating organs are covered by a nearly transparent membranous sac.

\begin{itemize}
\tightlist
\item
  \textbf{Gastroschisis (Q79.3)}
\end{itemize}

A congenital opening or fissure in the anterior abdominal wall lateral to the umbilicus through which the small intestine, part of the large intestine, and occasionally the liver and spleen, may herniate. The opening is separated from the umbilicus by a small bridge of skin, and the herniating organs are not covered by a protective membrane. Gastroschisis usually occurs on the right side of the umbilicus, although it may occur on the left.

\hypertarget{section21112}{%
\subsubsection{Selected chromosomal defects}\label{section21112}}

\begin{itemize}
\tightlist
\item
  \textbf{Down Syndrome (Q90)}
\end{itemize}

The presence of three copies of all or a large part of chromosome 21.

\begin{itemize}
\tightlist
\item
  \textbf{Trisomy 13 - Patau - (Q91.4-Q91.7)}
\end{itemize}

The presence of three copies of all or a large part of chromosome 13.

\begin{itemize}
\tightlist
\item
  \textbf{Trisomy 18 - Edwards - (Q91.0-Q91.3)}
\end{itemize}

The presence of three copies of all or a large part of chromosome 18.

\begin{itemize}
\tightlist
\item
  \textbf{Turner syndrome (Q96)}
\end{itemize}

Presence of an absent or structurally abnormal second X chromosome in a phenotypic female.

\hypertarget{chapter3}{%
\chapter{Anomalies Overview}\label{chapter3}}

\hypertarget{section32}{%
\section{Neural tube defects}\label{section32}}

At a \(5\%\) level, there is no significant trend for neural tube defects (\(\hat{\beta_{1}} =\) 0.040, p-value = 0.363) for the period 2013 - 2022.

Over the past 11 years (2013-2023), there is no evidence showing any trend in the prevalence rate of neural tube defects. On average, the prevalence rate for each subsequent year is 1.040 times of the previous year's rate: (prevalence rate = exp(0.040) = 1.040 per 10,000 total births; \(\hat{\beta_{1}} =\) 0.040, p-value = 0.363; \(95\%\) CI for \(\hat{\beta_{1}}\) and for the prevalence rate are given by \(CI(95\%)_{\hat{\beta_{1}}}\):{[}-0.046; 0.125{]}, and \(CI(95\%)_{rate}\):{[}0.955; 1.133{]}, respectively).

\begin{figure}[h]

{\centering \includegraphics[width=1\linewidth,]{02-Trend_files/figure-latex/nt1-1} 

}

\caption{Neural tube defects - Prevalence - Nova Scotia - 2013-2022}\label{fig:nt1}
\end{figure}

Based on the statistical analysis, at a \(5\%\) level, it is possible to observe:

\begin{itemize}
\item
  (Q00) - Anencephaly and similar malformations: there is no significant trend (\(\hat{\beta_{1}} =\) -0.056, p-value = 0.394).
\item
  (Q01) - Encephalocele: there is no significant trend (\(\hat{\beta_{1}} =\) -0.196, p-value = 0.144).
\item
  (Q05) - Spina bifida: there is evidence of an increasing trend (\(\hat{\beta_{1}} =\) 0.175, p-value = 0.021).
\end{itemize}

\begin{figure}[h]

{\centering \includegraphics[width=1\linewidth,]{02-Trend_files/figure-latex/nt11-1} 

}

\caption{(Q00) - Anencephaly and similar malformations - Prevalence.}\label{fig:nt11}
\end{figure}

\begin{figure}[h]

{\centering \includegraphics[width=1\linewidth,]{02-Trend_files/figure-latex/nt12-1} 

}

\caption{(Q01) - Encephalocele - Prevalence.}\label{fig:nt12}
\end{figure}

\begin{figure}[h]

{\centering \includegraphics[width=0.65\linewidth,]{02-Trend_files/figure-latex/nt13-1} 

}

\caption{(Q05) - Spina bifida - Prevalence.}\label{fig:nt13}
\end{figure}

\clearpage

\hypertarget{section33}{%
\section{Selected central nervous system defects}\label{section33}}

\clearpage

\hypertarget{section34}{%
\section{Selected sense organ defects}\label{section34}}

\clearpage

\hypertarget{section35}{%
\section{Selected congenital heart defects}\label{section35}}

\clearpage

\hypertarget{appendix}{%
\chapter*{Appendix}\label{appendix}}


The following table of selected sentinel anomalies indicate the trends in congenital anomaly prevalence in Nova Scotia from 1987 through 2023. Sentinel anomalies are those which the International Clearinghouse of Birth Defects Surveillance and Research (ICBDSR), of which we are a member, watches worldwide with the rationale that they are quite easily identified hence more accurately reported. \emph{See Section} \ref{section21} \emph{for all the anomalies listed in the report.}

\hypertarget{section-a1}{%
\section{Appendix 1 - Linear trend analysis and p-values, 2013-2022}\label{section-a1}}

\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{>{\raggedright\arraybackslash}p{4cm}cccc}
\toprule
Selected anomaly & \makecell[c]{Number of\\ cases} & \makecell[c]{Trend \\ direction} & \makecell[c]{Statistic \\ $\left(\chi^{2}_{1}\right)$} & P-value\\
\midrule
\endfirsthead
\multicolumn{5}{@{}l}{\textit{(continued)}}\\
\toprule
Selected anomaly & \makecell[c]{Number of\\ cases} & \makecell[c]{Trend \\ direction} & \makecell[c]{Statistic \\ $\left(\chi^{2}_{1}\right)$} & P-value\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
Neural tube defects & 64 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.83 & 0.363\\
(Q00) - Anencephaly and similar malformations & 29 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.73 & 0.394\\
(Q01) - Encephalocele & 6 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 2.14 & 0.144\\
(Q05) - Spina bifida & 29 & Increasing $\left(\uparrow \right)$ & 5.33 & 0.021\\
Selected central nervous system defects & 108 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.15 & 0.697\\
\addlinespace
(Q02) - Microcephaly & 53 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.02 & 0.901\\
(Q03) - Congenital hydrocephalus & 50 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 1.28 & 0.257\\
(Q04.1, Q04.2) - Arhinencephaly / Holoprosencephaly & 9 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.06 & 0.809\\
Selected sense organ defects & 28 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 1.31 & 0.252\\
(Q11.0-Q11.2) - Anophtalmos / Microphtalmos & 7 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.60 & 0.437\\
\addlinespace
(Q16.0, Q17.2) - Anotia / Microtia & 14 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.05 & 0.819\\
(Q30.0) - Choanal atresia & 9 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 1.92 & 0.166\\
Selected congenital heart defects & 211 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.33 & 0.564\\
(Q20.0) - Commom truncus & 11 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.12 & 0.724\\
(Q20.1, Q20.3, Q20.5) - Transposition of great vessels & 59 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 1.60 & 0.206\\
\addlinespace
(Q21.2) - Atrioventricular septal defect & 71 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.61 & 0.434\\
(Q21.3) - Tetralogy of Fallot & 33 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.02 & 0.901\\
(Q23.4) - Hypoplastic left heart syndrome & 28 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.71 & 0.401\\
(Q25.1) - Coarctation of aorta & 54 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.05 & 0.820\\
Oro-facial clefts & 102 & Increasing $\left(\uparrow \right)$ & 5.39 & 0.020\\
\addlinespace
(Q35) - Cleft palate only & 67 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 1.69 & 0.194\\
(Q36) - Cleft lip only & 18 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 1.41 & 0.236\\
(Q37) - Cleft palate with cleft lip & 39 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 2.84 & 0.092\\
Selected gastrointestinal defects & 112 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 1.83 & 0.176\\
(Q39.0-Q39.4) - Oesophageal atresia / stenosis, tracheoesophageal fistula & 29 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.33 & 0.566\\
\addlinespace
(Q41) - Small intestine absence / atresia / stenosis & 32 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 1.28 & 0.257\\
(Q42.0-Q42.3) - Ano-rectal absence / atresia / stenosis & 31 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 1.38 & 0.240\\
(Q43.1) - Hirschsprung disease & 17 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.41 & 0.521\\
(Q44.2) - Atresia of bile ducts & 9 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.16 & 0.694\\
Selected genital anomalies & 561 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.03 & 0.871\\
\addlinespace
(Q53.1, Q53.2, Q53.9) - Cryptorchidism / undescended testicles & 262 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.19 & 0.663\\
(Q54, excluding Q54.4) - Hypospadias & 276 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 2.77 & 0.096\\
(Q56) - Indeterminate sex & 24 & Increasing $\left(\uparrow \right)$ & 5.01 & 0.025\\
(Q64.0) - Epispadias & 8 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.88 & 0.349\\
Selected urinary tract defects & 163 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 1.78 & 0.182\\
\addlinespace
(Q60.0-Q60.2) - Renal agenesis & 74 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 3.23 & 0.072\\
(Q61.1-Q61.5, Q61.8, Q61.9) - Cystic kidney & 79 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.33 & 0.568\\
(Q64.1) - Bladder and cloacal exstrophy & 4 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.00 & 0.991\\
(Q64.2, Q64.3) - Lower urinary tract obstruction & 20 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.57 & 0.451\\
Hip dysplasia & 214 & Decreasing $\left(\downarrow \right)$ & 7.85 & 0.005\\
\addlinespace
Limb deficiency defects & 30 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 2.22 & 0.136\\
Selected abdominal wall defects & 88 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 2.06 & 0.152\\
(Q79.2) - Omphalocele / Exomphalos & 27 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.19 & 0.660\\
(Q79.3) - Gastroschisis & 34 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.38 & 0.537\\
Selected chromosomal defects & 172 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 1.05 & 0.306\\
\addlinespace
(Q90) - Down Syndrome & 121 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.36 & 0.546\\
(Q91.4-Q91.7) - Trisomy 13 - Patau & 11 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.03 & 0.868\\
(Q91.0-Q91.3) - Trisomy 18 - Edwards & 24 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.27 & 0.600\\
(Q96) - Turner syndrome & 17 & \makecell[c]{No significant \\ change $\left(\rightarrow \right)$} & 0.15 & 0.696\\*
\end{longtable}
\endgroup{}

\clearpage

\hypertarget{section-a2}{%
\section{Appendix 2 - Total birth, number of cases, anomalies and anomalies per case, 2013-2022}\label{section-a2}}

\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{ccccccc}
\toprule
Year & \makecell[c]{Total \\ births} & \makecell[c]{Number of \\ cases} & \makecell[c]{Case rate per \\ 10,000 total births} & \makecell[c]{Number of \\ anomalies} & \makecell[c]{Anomaly rate per \\ 10,000 total births} & \makecell[c]{Anomaly rate \\ per case}\\
\midrule
\endfirsthead
\multicolumn{7}{@{}l}{\textit{(continued)}}\\
\toprule
Year & \makecell[c]{Total \\ births} & \makecell[c]{Number of \\ cases} & \makecell[c]{Case rate per \\ 10,000 total births} & \makecell[c]{Number of \\ anomalies} & \makecell[c]{Anomaly rate per \\ 10,000 total births} & \makecell[c]{Anomaly rate \\ per case}\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
\cellcolor{gray!6}{2013} & \cellcolor{gray!6}{8443} & \cellcolor{gray!6}{191} & \cellcolor{gray!6}{226.22} & \cellcolor{gray!6}{218} & \cellcolor{gray!6}{258.20} & \cellcolor{gray!6}{1.14}\\
2014 & 8641 & 191 & 221.04 & 225 & 260.39 & 1.18\\
\cellcolor{gray!6}{2015} & \cellcolor{gray!6}{8160} & \cellcolor{gray!6}{161} & \cellcolor{gray!6}{197.30} & \cellcolor{gray!6}{177} & \cellcolor{gray!6}{216.91} & \cellcolor{gray!6}{1.10}\\
2016 & 8304 & 154 & 185.45 & 184 & 221.58 & 1.19\\
\cellcolor{gray!6}{2017} & \cellcolor{gray!6}{8242} & \cellcolor{gray!6}{157} & \cellcolor{gray!6}{190.49} & \cellcolor{gray!6}{185} & \cellcolor{gray!6}{224.46} & \cellcolor{gray!6}{1.18}\\
\addlinespace
2018 & 7939 & 151 & 190.20 & 197 & 248.14 & 1.30\\
\cellcolor{gray!6}{2019} & \cellcolor{gray!6}{8068} & \cellcolor{gray!6}{180} & \cellcolor{gray!6}{223.10} & \cellcolor{gray!6}{221} & \cellcolor{gray!6}{273.92} & \cellcolor{gray!6}{1.23}\\
2020 & 7600 & 163 & 214.47 & 183 & 240.79 & 1.12\\
\cellcolor{gray!6}{2021} & \cellcolor{gray!6}{8139} & \cellcolor{gray!6}{168} & \cellcolor{gray!6}{206.41} & \cellcolor{gray!6}{199} & \cellcolor{gray!6}{244.50} & \cellcolor{gray!6}{1.18}\\
2022 & 7856 & 148 & 188.39 & 168 & 213.85 & 1.14\\*
\end{longtable}
\endgroup{}

\hypertarget{section-a23}{%
\section{Appendix 3 - Prevalence rate per 10,000 total births, aggregated prevalence rate, 2013-2022}\label{section-a23}}

\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{>{\raggedright\arraybackslash}m{4cm}cc>{}c}
\toprule
Selected anomaly & \makecell[c]{Number of \\ cases} & \makecell[c]{Aggregated prevalence rate per \\ 10,000 total births \\ (2012-2022)} & \makecell[c]{Prevalence rate per \\ 10,000 total births \\ (2012-2022)}\\
\midrule
\endfirsthead
\multicolumn{4}{@{}l}{\textit{(continued)}}\\
\toprule
Selected anomaly & \makecell[c]{Number of \\ cases} & \makecell[c]{Aggregated prevalence rate per \\ 10,000 total births \\ (2012-2022)} & \makecell[c]{Prevalence rate per \\ 10,000 total births \\ (2012-2022)}\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
\cellcolor{gray!6}{Neural tube defects} & \cellcolor{gray!6}{64} & \cellcolor{gray!6}{1.226} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f44a12631.pdf}\\
(Q00) - Anencephaly and similar malformations & 29 & 1.215 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f414a11ff2.pdf}\\
\cellcolor{gray!6}{(Q01) - Encephalocele} & \cellcolor{gray!6}{6} & \cellcolor{gray!6}{1.204} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f47be057c7.pdf}\\
(Q05) - Spina bifida & 29 & 1.243 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f448ad4b46.pdf}\\
\cellcolor{gray!6}{Selected central nervous system defects} & \cellcolor{gray!6}{108} & \cellcolor{gray!6}{1.228} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f471763c51.pdf}\\
\addlinespace
(Q02) - Microcephaly & 53 & 1.229 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f474272bf2.pdf}\\
\cellcolor{gray!6}{(Q03) - Congenital hydrocephalus} & \cellcolor{gray!6}{50} & \cellcolor{gray!6}{1.225} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f47fb37c8a.pdf}\\
(Q04.1, Q04.2) - Arhinencephaly / Holoprosencephaly & 9 & 1.260 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f45bef7f2b.pdf}\\
\cellcolor{gray!6}{Selected sense organ defects} & \cellcolor{gray!6}{28} & \cellcolor{gray!6}{1.214} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f43a77042.pdf}\\
(Q11.0-Q11.2) - Anophtalmos / Microphtalmos & 7 & 1.225 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f424ec2779.pdf}\\
\addlinespace
\cellcolor{gray!6}{(Q16.0, Q17.2) - Anotia / Microtia} & \cellcolor{gray!6}{14} & \cellcolor{gray!6}{1.218} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f47bab7edb.pdf}\\
(Q30.0) - Choanal atresia & 9 & 1.201 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f43a843539.pdf}\\
\cellcolor{gray!6}{Selected congenital heart defects} & \cellcolor{gray!6}{211} & \cellcolor{gray!6}{1.226} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f475d84fcd.pdf}\\
(Q20.0) - Commom truncus & 11 & 1.213 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f445243f1e.pdf}\\
\cellcolor{gray!6}{(Q20.1, Q20.3, Q20.5) - Transposition of great vessels} & \cellcolor{gray!6}{59} & \cellcolor{gray!6}{1.228} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f4e8e4b23.pdf}\\
\addlinespace
(Q21.2) - Atrioventricular septal defect & 71 & 1.228 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f430beaab.pdf}\\
\cellcolor{gray!6}{(Q21.3) - Tetralogy of Fallot} & \cellcolor{gray!6}{33} & \cellcolor{gray!6}{1.224} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f47eef69fd.pdf}\\
(Q23.4) - Hypoplastic left heart syndrome & 28 & 1.218 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f443464bb.pdf}\\
\cellcolor{gray!6}{(Q25.1) - Coarctation of aorta} & \cellcolor{gray!6}{54} & \cellcolor{gray!6}{1.225} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f43b62570c.pdf}\\
Oro-facial clefts & 102 & 1.235 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f443349f9.pdf}\\
\addlinespace
\cellcolor{gray!6}{(Q35) - Cleft palate only} & \cellcolor{gray!6}{67} & \cellcolor{gray!6}{1.231} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f422115f18.pdf}\\
(Q36) - Cleft lip only & 18 & 1.258 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f42e057f68.pdf}\\
\cellcolor{gray!6}{(Q37) - Cleft palate with cleft lip} & \cellcolor{gray!6}{39} & \cellcolor{gray!6}{1.231} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f4396b317d.pdf}\\
Selected gastrointestinal defects & 112 & 1.218 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f47eba3add.pdf}\\
\cellcolor{gray!6}{(Q39.0-Q39.4) - Oesophageal atresia / stenosis, tracheoesophageal fistula} & \cellcolor{gray!6}{29} & \cellcolor{gray!6}{1.218} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f47ea270a9.pdf}\\
\addlinespace
(Q41) - Small intestine absence / atresia / stenosis & 32 & 1.214 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f44583b80.pdf}\\
\cellcolor{gray!6}{(Q42.0-Q42.3) - Ano-rectal absence / atresia / stenosis} & \cellcolor{gray!6}{31} & \cellcolor{gray!6}{1.224} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f4442e12a0.pdf}\\
(Q43.1) - Hirschsprung disease & 17 & 1.218 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f44866324e.pdf}\\
\cellcolor{gray!6}{(Q44.2) - Atresia of bile ducts} & \cellcolor{gray!6}{9} & \cellcolor{gray!6}{1.205} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f420481179.pdf}\\
Selected genital anomalies & 561 & 1.228 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f45725a9a.pdf}\\
\addlinespace
\cellcolor{gray!6}{(Q53.1, Q53.2, Q53.9) - Cryptorchidism / undescended testicles} & \cellcolor{gray!6}{262} & \cellcolor{gray!6}{1.232} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f46b706bde.pdf}\\
(Q54, excluding Q54.4) - Hypospadias & 276 & 1.223 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f42d8c2287.pdf}\\
\cellcolor{gray!6}{(Q56) - Indeterminate sex} & \cellcolor{gray!6}{24} & \cellcolor{gray!6}{1.237} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f44ee7758f.pdf}\\
(Q64.0) - Epispadias & 8 & 1.240 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f4c9238f.pdf}\\
\cellcolor{gray!6}{Selected urinary tract defects} & \cellcolor{gray!6}{163} & \cellcolor{gray!6}{1.228} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f4633677e0.pdf}\\
\addlinespace
(Q60.0-Q60.2) - Renal agenesis & 74 & 1.229 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f433c26b00.pdf}\\
\cellcolor{gray!6}{(Q61.1-Q61.5, Q61.8, Q61.9) - Cystic kidney} & \cellcolor{gray!6}{79} & \cellcolor{gray!6}{1.227} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f45ea62237.pdf}\\
(Q64.1) - Bladder and cloacal exstrophy & 4 & 1.224 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f42612127a.pdf}\\
\cellcolor{gray!6}{(Q64.2, Q64.3) - Lower urinary tract obstruction} & \cellcolor{gray!6}{20} & \cellcolor{gray!6}{1.222} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f453c54a8f.pdf}\\
Hip dysplasia & 214 & 1.223 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f428dc2872.pdf}\\
\addlinespace
\cellcolor{gray!6}{(Q65) - Hip dysplasia} & \cellcolor{gray!6}{214} & \cellcolor{gray!6}{1.223} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f47fe77df8.pdf}\\
Limb deficiency defects & 30 & 1.211 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f4554268b2.pdf}\\
\cellcolor{gray!6}{(Q79.0) - Diaphragmatic hernia} & \cellcolor{gray!6}{28} & \cellcolor{gray!6}{1.239} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f429a36114.pdf}\\
(Q71.4-Q71.9, Q72.4-Q72.9, Q73.8, excluding Q71.6, Q71.7, Q72.7) - Limb deficiency defects & 30 & 1.211 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f472ef44d6.pdf}\\
\cellcolor{gray!6}{Selected abdominal wall defects} & \cellcolor{gray!6}{88} & \cellcolor{gray!6}{1.231} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f4f52609b.pdf}\\
\addlinespace
(Q79.2) - Omphalocele / Exomphalos & 27 & 1.230 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f46e8e3cd1.pdf}\\
\cellcolor{gray!6}{(Q79.3) - Gastroschisis} & \cellcolor{gray!6}{34} & \cellcolor{gray!6}{1.225} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f4659331d8.pdf}\\
Selected chromosomal defects & 172 & 1.225 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f46051766.pdf}\\
\cellcolor{gray!6}{(Q90) - Down Syndrome} & \cellcolor{gray!6}{121} & \cellcolor{gray!6}{1.225} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f465ca232a.pdf}\\
(Q91.4-Q91.7) - Trisomy 13 - Patau & 11 & 1.236 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f4226baaf.pdf}\\
\addlinespace
\cellcolor{gray!6}{(Q91.0-Q91.3) - Trisomy 18 - Edwards} & \cellcolor{gray!6}{24} & \cellcolor{gray!6}{1.230} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f46c9c3c84.pdf}\\
(Q96) - Turner syndrome & 17 & 1.210 & \includegraphics[width=0.67in, height=0.17in]{H:/RCP/RCP_Data/TeixeiEC/Anomalies/anomaly-report/03-Appendix_files/figure-latex/plot_11f47796249a.pdf}\\*
\end{longtable}
\endgroup{}


\end{document}
